<?php
defined('_JEXEC') or die('restricted access');

class MkartaModelAnalysis extends JModelItem {

    protected $item;

    protected function populateState()
    {
        //parent::populateState(); // TODO: Change the autogenerated stub

        $input = JFactory::getApplication()->input;
        $id = $input->get('id',0,'INT');
        $this->setState('item.id',$id);
    }

    public function getItem(){

        $id = $this->getState('item.id');

        //var_dump($id);

        $db = JFactory::getDbo();
        $query = $db->getQuery(true);
        $query->select('`id`,`created_by`,`explanation`,`type_of_analysis`, `image`,`date`,`adder_id`');
        $query->from('#__analyses');
        $query->where('id='.(int)$id);
        $db->setQuery($query);
        $this->item = $db->loadObject();
        return $this->item;

    }
}