<?php
// No direct access to this file
defined('_JEXEC') or die('Restricted access');


class MkartaModelAnalyses extends JModelList
{
    protected function getListQuery()
    {
        //return parent::getListQuery(); // TODO: Change the autogenerated stub
        $db = JFactory::getDbo();
        $query = $db->getQuery(true);

        $query->select('`id`, `created_by`, `explanation`, `type_of_analysis`,`image`,`date`,`adder_id`');

        $query->from('#__analyses');
        $query->order('`id` DESC');

        return $query;
    }
}