<?php
defined('_JEXEC') or die('restricted access');

class MkartaModelAnalysis extends JModelItem {

    protected $item;

    protected function populateState()
    {
        //parent::populateState(); // TODO: Change the autogenerated stub

        $input = JFactory::getApplication()->input;
        $id = $input->get('id',0,'INT');
        $this->setState('item.id',$id);

        // Load the parameters.
        $this->setState('params', JFactory::getApplication()->getParams());
        parent::populateState();

    }

    public function getItem(){

        $id = $this->getState('item.id');

        //var_dump($id);

        $db = JFactory::getDbo();
        $query = $db->getQuery(true);
        $query->select('a.id,a.created_by,a.explanation,a.type_of_analysis, a.image,a.date,a.adder_id,a.params,a.image as image, c.title as category');
        $query->from('#__analyses as a');
        $query->leftJoin('#__categories as c ON a.catid=c.id');
        $query->where('a.id='.(int)$id);
        $db->setQuery($query);



        if ($this->item = $db->loadObject())
        {
            // Load the JSON string
            $params = new JRegistry;
            $params->loadString($this->item->params, 'JSON');
            $this->item->params = $params;

            // Merge global params with item params
            $params = clone $this->getState('params');
            $params->merge($this->item->params);
            $this->item->params = $params;

            // Convert the JSON-encoded image info into an array
            $image = new JRegistry;
            $image->loadString($this->item->image, 'JSON');
            $this->item->imageDetails = $image;

        }



        return $this->item;

    }
}