<?php
// No direct access to this file
defined('_JEXEC') or die('Restricted access');

class MkartaControllerAnalysis_form extends JControllerForm {

    public function save($key = null, $urlVar = null)
    {
        var_dump($_POST);



        //return parent::save($key, $urlVar); // TODO: Change the autogenerated stub
    }

public function cancel($key = null)
{
    parent::cancel($key);

    // set up the redirect back to the same form
    $this->setRedirect(
        (string)JUri::getInstance(),
        JText::_('COM_MKARTA_ADD_CANCELLED')
    );



}

}